### ISSUE TITLE
concurrentmodificationexception异常

### ISSUE THREAD

**Issue by cllstudy** [xuexiangjys/RxUtil2#2]
RxUtils2版本:1.1.5,下面是全部异常信息:
崩溃信息:
null

类名:RPSlamwareSdpAgent.java

方法:run

行数:1094

类型:java.util.ConcurrentModificationException

时间:2021-04-23_13:46

设备名称:MED-AL00

设备厂商:HUAWEI

系统版本:Android 10-29

CPU-ABI:armeabi-v7a

versionCode:14

versionName:V1.0.4

全部信息:
java.util.ConcurrentModificationException
 at java.util.ArrayList$Itr.next(ArrayList.java:860)
 at com.xuexiang.rxutil2.rxbus.RxBus.post(RxBus.java:135)
 at com.xuexiang.rxutil2.rxbus.RxBus.post(RxBus.java:123)
 at com.xuexiang.rxutil2.rxbus.RxBusUtils.post(RxBusUtils.java:269)
 at com.csjbot.robotstation.agent.RPSlamwareSdpAgent$JobRobotPose.run(RPSlamwareSdpAgent.java:1094)
 at com.csjbot.robotstation.agent.Worker$1.run(Worker.java:42)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:929)

**Comment by xuexiangjys** [comment]
已修复:
7cd4b9e4a7e6025ba6dcb104e5573b80d90186d3
